/**
 * One-time setup of LOCAL Supabase for development and tests.
 *
 *   supabase start                     # needs Docker; applies supabase/migrations 0001-0006
 *   npx tsx scripts/local-setup.ts     # this script
 *
 * 1. Reads the local URLs/keys from `supabase status` and writes .env.test.local
 *    (gitignored). Refuses anything that isn't localhost.
 * 2. Creates a local admin (admin@local.test) and writes its id as ADMIN_UID.
 * 3. Loads the question bank + demo role assessments (scripts/seed.ts).
 * 4. Creates the Common Aptitude Assessment and removes the per-role Aptitude
 *    sections (scripts/setup-common-aptitude.ts --apply).
 *
 * Safe to re-run: step 2 reuses the admin, seed/aptitude steps skip what exists.
 */
import { execSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { writeFileSync } from "node:fs";
import { WebSocket } from "ws";
import { createClient } from "@supabase/supabase-js";
import { DEFAULT_ENV_FILE } from "./target-env";

if (!("WebSocket" in globalThis)) (globalThis as unknown as { WebSocket: typeof WebSocket }).WebSocket = WebSocket;

const CLI = process.env.SUPABASE_CLI ?? "supabase";
const ADMIN_EMAIL = "admin@local.test";

function pick(status: Record<string, string>, ...keys: string[]) {
  for (const k of keys) if (status[k]) return status[k];
  throw new Error(`\`${CLI} status\` has none of: ${keys.join(", ")}`);
}

async function main() {
  const status = JSON.parse(execSync(`${CLI} status -o json`, { encoding: "utf8", stdio: ["ignore", "pipe", "inherit"] })) as Record<string, string>;
  const url = pick(status, "API_URL");
  if (!/^https?:\/\/(127\.0\.0\.1|localhost)(:\d+)?$/.test(url)) throw new Error(`Not a local Supabase URL: ${url}`);
  const publishableKey = pick(status, "PUBLISHABLE_KEY", "ANON_KEY");
  const serviceKey = pick(status, "SERVICE_ROLE_KEY", "SECRET_KEY");
  const dbUrl = pick(status, "DB_URL");

  const admin = createClient(url, serviceKey, { auth: { persistSession: false, autoRefreshToken: false } });
  const { data: users } = await admin.auth.admin.listUsers();
  let adminUser = users?.users.find((u) => u.email === ADMIN_EMAIL);
  let password = "(unchanged - reset with: npm run reset-admin-password -- <new password>)";
  if (!adminUser) {
    password = `Local-${randomBytes(6).toString("hex")}`;
    const { data, error } = await admin.auth.admin.createUser({ email: ADMIN_EMAIL, password, email_confirm: true });
    if (error || !data.user) throw error ?? new Error("could not create local admin");
    adminUser = data.user;
  }
  const { error: profileError } = await admin.from("profiles").upsert({ id: adminUser.id, email: ADMIN_EMAIL, role: "admin" }, { onConflict: "id" });
  if (profileError) throw profileError;

  writeFileSync(
    DEFAULT_ENV_FILE,
    [
      "# LOCAL Supabase (generated by scripts/local-setup.ts - do not commit)",
      `NEXT_PUBLIC_SUPABASE_URL=${url}`,
      `NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${publishableKey}`,
      `SUPABASE_SERVICE_ROLE_KEY=${serviceKey}`,
      `SUPABASE_DB_URL=${dbUrl}`,
      `ADMIN_UID=${adminUser.id}`,
      "NEXT_PUBLIC_APP_URL=http://localhost:3000",
      "",
    ].join("\n")
  );
  console.log(`Wrote ${DEFAULT_ENV_FILE} (${url}). Local admin: ${ADMIN_EMAIL} / ${password}`);

  const env = { ...process.env, SUPABASE_ENV_FILE: DEFAULT_ENV_FILE };
  const { count } = await admin.from("questions").select("id", { count: "exact", head: true });
  if (!count) execSync("npx tsx scripts/seed.ts", { stdio: "inherit", env });
  else console.log(`Question bank already loaded (${count} questions) - skipping seed.`);
  execSync("npx tsx scripts/setup-common-aptitude.ts --apply", { stdio: "inherit", env });
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
